datalogger:
  # type >> controller type
  # supported controllers: uvr42
  # default: uvr42
  type: uvr42

dlbus:
  # gpio >> DL-Bus input gpio pin
  gpio: 4
  # debounceperiod >> time to wait for a stable signal on gpio pin (micro seconds)
  #                   to get a "clean" level (suppress key bouncing)
  # default: 0
  debounceperiod: 0
  # terminator defines the termination of the gpio line
  # supported values: pullup | pulldown | none
  # default: none
  terminator: none

# log activates the debug level and the output device/file
log:
  # log file e.g. /tmp/emu.log; stderr; stdout
  # default: stderr
  file: stderr
  # flag: (default: Error)
  #  Warning | Info | Error | Fatal | Debug | Trace
  flag: Error

mqtt:
  # connection >> defines the connection string to the mqtt broker
  connection: "tcp://raspberrypi4.fritz.box:1883"
  # topic is the mqtt topic where the measurement sent
  topic: test/uvr42/summary
  # interval defines the interval in seconds, in which the measurements are sent to mqqt
  # the value 0 means, data are only sent when the temperature changes (see parameter deltakelvin)
  # default 5s
  interval: 60
  # deltakelvin defines the value by which a temperature value must at least change in order for data to be sent to mqtt
  # the value 0 means, data are only sent by interval (see parameter interval)
  # default 0.5K
  deltakelvin: 0.5

# webserver configuration
webserver:
  # url defines the bound of host (default: 0.0.0.0:4000)
  url: http://0.0.0.0:4020
  # enable/disable webservices (default: disabled)
  webservices:
    version: true
    health: true
    data: true