// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the latest available values read from the configured data logger.\nThe response structure depends on the configured device type:\nUVR42 returns temperature1–4, out1, out2 and a timestamp.\nUVR31 returns temperature1–3, out1 and a timestamp.\nA temperature outside the sensor range is left out.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get current data logger values",
                "responses": {
                    "200": {
                        "description": "Current data logger values",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "out1": {
                                    "type": "boolean"
                                },
                                "out2": {
                                    "type": "boolean"
                                },
                                "temperature1": {
                                    "type": "number"
                                },
                                "temperature2": {
                                    "type": "number"
                                },
                                "temperature3": {
                                    "type": "number"
                                },
                                "temperature4": {
                                    "type": "number"
                                },
                                "timestamp": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "No frame received yet, or the last one is stale",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves memory usage, goroutine count, version, hostname, Go runtime version and OS, the MQTT connection state,\nthe latest controller values with their names, bar ranges and 15 min trend, and the state of the DL-Bus input\n(signal, bit rate, line polarity, error counters since start and for the last 24 h). The web UI at / reads it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get health data",
                "responses": {
                    "200": {
                        "description": "Health data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/health.Model"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current application name and version. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get application version and name",
                "responses": {
                    "200": {
                        "description": "Application version and name",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "app": {
                                    "type": "string"
                                },
                                "appVersion": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "collector.DataloggerStatus": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "boolean"
                },
                "lastFrame": {
                    "type": "string"
                },
                "lastFrameAgeSeconds": {
                    "type": "number"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/collector.OutputStatus"
                    }
                },
                "temperatures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/collector.TemperatureStatus"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "collector.OutputStatus": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "on": {
                    "type": "boolean"
                }
            }
        },
        "collector.TemperatureStatus": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "max": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                },
                "trend15m": {
                    "description": "Trend15m is the change in Kelvin over the last 15 minutes; null until\ntadl has run that long or while the sensor is out of range.",
                    "type": "number"
                },
                "value": {
                    "description": "null: sensor out of range",
                    "type": "number"
                }
            }
        },
        "health.BusStatus": {
            "type": "object",
            "properties": {
                "bitRateHz": {
                    "description": "recovered bit clock; null while the decoder searches for it",
                    "type": "number"
                },
                "decoder": {
                    "description": "decoder state as text, for troubleshooting",
                    "type": "string"
                },
                "droppedEdges": {
                    "type": "integer"
                },
                "droppedFrames": {
                    "type": "integer"
                },
                "errors24h": {
                    "$ref": "#/definitions/health.ErrorSummary"
                },
                "framesReceived": {
                    "description": "Cumulative counters since start.",
                    "type": "integer"
                },
                "invertedLine": {
                    "type": "boolean"
                },
                "lastError": {
                    "description": "last error within the last 24 h; null if none",
                    "type": "string"
                },
                "lastErrorAgeSeconds": {
                    "type": "number"
                },
                "protocolErrors": {
                    "type": "integer"
                },
                "rejectedFrames": {
                    "type": "integer"
                },
                "signal": {
                    "type": "string"
                }
            }
        },
        "health.ErrorSummary": {
            "type": "object",
            "properties": {
                "droppedEdges": {
                    "description": "GPIO edges lost before decoding",
                    "type": "integer"
                },
                "droppedFrames": {
                    "description": "frames discarded because the reader was busy",
                    "type": "integer"
                },
                "protocolErrors": {
                    "description": "frames discarded for a missing stop bit",
                    "type": "integer"
                },
                "rejectedFrames": {
                    "description": "frames of the wrong size or device, or without a valid temperature",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "health.Model": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "Application name (MODULE)",
                    "type": "string"
                },
                "appVersion": {
                    "description": "Current version of the application",
                    "type": "string"
                },
                "bus": {
                    "description": "state of the DL-Bus input",
                    "allOf": [
                        {
                            "$ref": "#/definitions/health.BusStatus"
                        }
                    ]
                },
                "datalogger": {
                    "description": "latest values of the controller",
                    "allOf": [
                        {
                            "$ref": "#/definitions/collector.DataloggerStatus"
                        }
                    ]
                },
                "goVersion": {
                    "description": "Go runtime version",
                    "type": "string"
                },
                "heapAllocBytes": {
                    "description": "Allocated heap memory in bytes",
                    "type": "integer"
                },
                "hostname": {
                    "description": "Machine name where the app runs",
                    "type": "string"
                },
                "mqtt": {
                    "description": "connected | disconnected | disabled",
                    "type": "string"
                },
                "numGoroutines": {
                    "description": "Current number of active goroutines",
                    "type": "integer"
                },
                "os": {
                    "description": "Operating system name",
                    "type": "string"
                },
                "sysMemoryBytes": {
                    "description": "Total memory obtained from the OS",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "UTC timestamp when health info was collected (RFC3339)",
                    "type": "string"
                },
                "uptimeSeconds": {
                    "description": "Application uptime in seconds",
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
